library(dplyr)
library(tidyr)

#' Read isomiR data
#'
#' This function allows to read given file produced by XICRA pipeline
#' containing unique ID for isomiR, variant type, UID and miRNA name
#' @param file_given miRNAexpression table generated by XICRA
#' @keywords XICRA
#' @export
prepare_data <- function(file_given) {
  ## Read table, split ID and fill_NA  #####
  ## Data
  read_table_given <- read.csv(file = file_given, header=TRUE, quote = '"')

  ### split isomiR_ID into for more information
  ### e.g. hsa-let-7a-3p&iso_3p:+1&rNsrq0Ov2 hsa-let-7a-3p iso_3p:+1 rNsrq0Ov2
  read_table_given <- tidyr::separate(read_table_given, ID, c('parent', 'variant', 'UID'), sep = '&', remove=FALSE)

  ## replace na variants
  read_table_given$variant <- as.character(read_table_given$variant)
  read_table_given$variant[read_table_given$variant == "NA"] <- "Canonical"

  ### replace na
  read_table_given[is.na(read_table_given)] <- 0

  return(read_table_given)
}

#' Summarize counts by miRNA
#'
#' This function allows to summarize isomiR data by miRNA
#' @param dataframe obtain from XICRA.stats::prepare_data
#' @keywords XICRA
#' @export
prepare_counts_by_miRNA <- function(dataGiven){
  cols.dont.want <- c("ID", "variant", "UID") # if you want to remove multiple columns
  count_data <-dataGiven[, ! names(dataGiven) %in% cols.dont.want, drop = F]
  count_data_summary <- count_data %>% dplyr::group_by(parent) %>% dplyr::summarise_if(is.numeric, sum) %>% as.data.frame()
  return(count_data_summary)
}

#' Summarize counts by miRNA & variant
#'
#' This function allows to summarize isomiR data by miRNA and variant type
#' @param dataframe obtain from XICRA.stats::prepare_data
#' @keywords XICRA
#' @export
prepare_counts_by_variant <- function(dataGiven) {
  cols.dont.want <- c("ID", "UID") # if you want to remove multiple columns
  count_data <-dataGiven[, ! names(dataGiven) %in% cols.dont.want, drop = F]
  count_data_summary <- count_data %>% dplyr::group_by(parent, variant) %>% dplyr::summarise_if(is.numeric, sum) %>% as.data.frame()
  return(count_data_summary)
}
