#' Read isomiR data
#'
#' This function allows to read given file produced by XICRA pipeline
#' containing unique ID for isomiR, variant type, UID and miRNA name
#' or table generated by DESeq2 with XICRA results contanining as Gene as unique
#' identifier. 
#' Provide type_data="DESeq2" or type_data="XICRA"
#' @param file_given miRNAexpression table generated by XICRA
#' @param type_data string (DESeq2 or XICRA)
#' @keywords XICRA
#' @export
prepare_data <- function(file_given, type_data) {
  require(dplyr)
  require(tidyr)
  
  ## Read table, split ID_given and fill_NA  #####
  if (type_data == 'XICRA') {
    ## Data
    read_table_given <- read.csv(file = file_given, header=TRUE)
    
    ### split isomiR_ID into for more information
    ### e.g. hsa-let-7a-3p&iso_3p:+1&rNsrq0Ov2 hsa-let-7a-3p iso_3p:+1 rNsrq0Ov2
    read_table_given <- tidyr::separate(read_table_given, ID, c('parent', 'variant', 'UID'), sep = '&', remove=FALSE)
  } 
  if (type_data == 'DESeq2') {
    ## Data
    read_table_given <- read.csv(file = file_given, header=TRUE, sep="\t")
    
    ### split isomiR_ID into for more information
    ### e.g. hsa-let-7a-3p&iso_3p:+1&rNsrq0Ov2 hsa-let-7a-3p iso_3p:+1 rNsrq0Ov2
    read_table_given <- tidyr::separate(read_table_given, Gene, c('parent', 'variant', 'UID'), sep = '&', remove=FALSE)
  } 
  
  read_table_given <- tidyr::separate(read_table_given, variant, c('type', 'int'), sep = ':', remove=FALSE)
  
  ## replace na variants string
  read_table_given$variant <- as.character(read_table_given$variant)
  read_table_given$variant[read_table_given$variant == "NA"] <- "Canonical"
  
  ### replace na
  read_table_given[is.na(read_table_given)] <- 0
  
  return(read_table_given)
}

#' Summarize counts by miRNA
#'
#' This function allows to summarize isomiR data by miRNA
#' @param dataframe obtain from XICRA.stats::prepare_data
#' @keywords XICRA
#' @export
prepare_counts_by_miRNA <- function(dataGiven){
  require(dplyr)
  require(tidyr)
  
  cols.dont.want <- c("ID", "variant", "UID") # if you want to remove multiple columns
  count_data <-dataGiven[, ! names(dataGiven) %in% cols.dont.want, drop = F]
  count_data_summary <- count_data %>% dplyr::group_by(parent) %>% dplyr::summarise_if(is.numeric, sum) %>% as.data.frame()
  return(count_data_summary)
}

#' Summarize counts by miRNA & variant
#'
#' This function allows to summarize isomiR data by miRNA and variant type
#' @param dataframe obtain from XICRA.stats::prepare_data
#' @keywords XICRA
#' @export
prepare_counts_by_variant <- function(dataGiven) {
  require(dplyr)
  require(tidyr)
  
  cols.dont.want <- c("ID", "UID") # if you want to remove multiple columns
  count_data <-dataGiven[, ! names(dataGiven) %in% cols.dont.want, drop = F]
  count_data_summary <- count_data %>% dplyr::group_by(parent, variant) %>% dplyr::summarise_if(is.numeric, sum) %>% as.data.frame()
  return(count_data_summary)
}

#' Read isomiR data and return: isormiR, miRNA and variant type
#'
#' This function allows to read given file produced by XICRA pipeline
#' containing unique ID and returns isomiR, variant type and miRNA data in
#' separate dataframes
#' @param file_given miRNAexpression table generated by XICRA
#' @keywords XICRA
#' @export
parse_XICRA <- function(XICRA_csv_file) {
  require(dplyr)
  require(tidyr)
  
  ## isomiR data
  isomir_data <- prepare_data(XICRA_csv_file, "XICRA")
  
  ## miRNA and variant data
  miRNA_data <- prepare_counts_by_miRNA(isomir_data)
  miRNA_variant_data <- prepare_counts_by_variant(isomir_data)
  
  ## create variants type
  miRNA_variant_data <- tidyr::separate(miRNA_variant_data, variant, c('type', 'int'), sep = ':', remove=FALSE)
  miRNA_variant_data$type <- as.character(miRNA_variant_data$type)
  
  # set rownames
  row.names(miRNA_data) <- miRNA_data$parent 
  row.names(isomir_data) <- isomir_data$ID
  
  ## remove columns
  miRNA_data$parent <- NULL
  
  isomir_data$parent <- NULL
  isomir_data$variant <- NULL
  isomir_data$UID <- NULL
  isomir_data$ID <- NULL
  
  miRNA_variant_data$int <- NULL
  
  ## return
  my_data <- list("isomir_data" = isomir_data, 
                  "miRNA_data"=miRNA_data, 
                  "miRNA_variant_data" = miRNA_variant_data)
  
  return (my_data)
}

#' Create statistics and gene sets for isomiR and miRNA from XICRA simulations
#'
#' This function allows to parse given dataframe produced XICRA simulations results
#' and generates statistics according to type of isomiR
#' @param data_df_given Dataframe from XICRA::prepare_data containing type, UID, parent column
#' @keywords XICRA
#' @export

create_geneSet_stats_simulations <- function(data_df){
  require(scales)
  
  ## create list from colum type
  geneset.list<-unique(data_df$type)
  
  #stats for data_df_given
  geneSet_stats<-data.frame(A=character(),B=numeric(),C=character(),D=integer(),E=character())
  colnames(geneSet_stats)<-c("class","average.read.counts","percent.avg.read.counts",
                             "n.unique","percent.diversity")
  geneSet_stats<-dplyr::slice(geneSet_stats,0)
  for (i in 1:length(geneset.list)){
    subset.i<-filter(data_df,type==geneset.list[i])
    geneSet_stats.i<-data.frame("class"=geneset.list[i],
                                "average.read.counts"=sum(subset.i$obs),
                                "percent.avg.read.counts"=percent((sum(subset.i$obs)/sum(data_df$obs)), accuracy=0.01),
                                "n.unique"=length(unique(subset.i$sequence)),
                                "percent.diversity"=percent(length(unique(subset.i$sequence))/length(unique(data_df$sequence)),accuracy=0.01))
    geneSet_stats<-bind_rows(geneSet_stats,geneSet_stats.i)
  }
  
  rownames(geneSet_stats) <- geneSet_stats$class
  geneSet_stats <- geneSet_stats[order(geneSet_stats$average.read.counts, decreasing = TRUE ),]
  return (geneSet_stats)
}

#' Create statistics and gene sets for isomiR and miRNA from XICRA data analyzed with DESeq2
#'
#' This function allows to parse given dataframe produced by DESeq2 from XICRA results
#' and generates statistics according to type of isomiR and genes sets in gmt format for
#' overrepresentation analysis
#' @param data_df_given Dataframe from XICRA::prepare_data containing type, UID, parent column
#' @param name tag for store results
#' @param path2store_results absolute path to store results produce
#' @keywords XICRA
#' @export
build_geneSet_collection_DESeq2 <- function(data_df_given, name, path2store_results) {
  
  require(scales)
  
  print ("+ Generate stats for DESeq2 dataframe provided")
  print ("+ Using column type")
  
  ## create list from colum type
  geneset.list<-unique(data_df_given$type)
  
  #stats for data_df_given
  geneSet_stats<-data.frame(A=character(),B=numeric(),C=character(),D=integer(),E=character())
  colnames(geneSet_stats)<-c("class","average.read.counts","percent.avg.read.counts",
                             "n.unique","percent.diversity")
  geneSet_stats<-dplyr::slice(geneSet_stats,0)
  
  for (i in 1:length(geneset.list)){
    subset.i<-filter(data_df_given,type==geneset.list[i])
    geneSet_stats.i<-data.frame("class"=geneset.list[i],
                                "average.read.counts"=round(sum(subset.i$baseMean),digits=0),
                                "percent.avg.read.counts"=percent((sum(subset.i$baseMean)/sum(data_df_given$baseMean)), accuracy=0.01),
                                "n.unique"=length(unique(subset.i$UID)),
                                "percent.diversity"=percent(length(unique(subset.i$UID))/length(unique(data_df_given$UID)),accuracy=0.01))
    geneSet_stats<-bind_rows(geneSet_stats,geneSet_stats.i)
  }
  
  rownames(geneSet_stats) <- geneSet_stats$class
  geneSet_stats <- geneSet_stats[order(geneSet_stats$average.read.counts, decreasing = TRUE ),]  
  
  print ("+ Stats generated")
  print (head(geneSet_stats))
  
  ## generate geneset.gmt for fgsea input -for analysis with fgsea package in R
  print ("+ Create geneset for FGSEA input at isomiR level")
  types_fgsea.gmt<-vector(mode = "list", length = length(geneset.list))
  names(types_fgsea.gmt)<-geneset.list
  
  #GSEA input -for analysis in java applet tool
  types_GSEA.gmt<-data.frame("name","description","ids")
  colnames(types_GSEA.gmt)<-c("name","description","ids")
  types_GSEA.gmt<-dplyr::slice(types_GSEA.gmt,0)
  
  for (i in 1:length(geneset.list)){
    names(types_fgsea.gmt)[i]<-geneset.list[i]
    isomirset.df.i<-data_df_given[data_df_given$type==geneset.list[i],c("type","UID")]
    fgsea.gmt.i <- isomirset.df.i %>% split(x = .$UID, f = .$type)
    isomirset.i<-paste(data_df_given$UID[data_df_given$type==geneset.list[i]],collapse='\t')
    geneset.i<-c(name=geneset.list[i],description="isomir_type",ids=isomirset.i)
    types_GSEA.gmt<-bind_rows(types_GSEA.gmt,geneset.i)
    types_fgsea.gmt[i]<-fgsea.gmt.i
  }
  
  ## types_fgsea.gmt
  print ("+ Gene set generated at isomiR level")
  print (head(types_fgsea.gmt))
  
  print ("+ Save geneset in file:")
  file_name_types_GSEA.gmt = file.path(path2store_results, paste0(name, "_isomir_types.gmt"))
  print (file_name_types_GSEA.gmt)
  write.table(types_GSEA.gmt,file_name_types_GSEA.gmt,sep="\t",row.names=F,col.names=F, quote=F)
  
  ###by miRNA isomiR correspondence
  print ("+ Create geneset for miRNA isomiR correspondence")
  print ("+ Using column parent")
  
  miRNAs_GSEA.gmt<-data.frame("name","description","ids")
  colnames(miRNAs_GSEA.gmt)<-c("name","description","ids")
  miRNAs_GSEA.gmt<-dplyr::slice(miRNAs_GSEA.gmt,0)
  miRNAset.list<-unique(data_df_given$parent)
  
  #fgsea input -for analysis with fgsea package in R
  miRNAs_fgsea.gmt<-vector(mode = "list", length = length(miRNAset.list))
  names(miRNAs_fgsea.gmt)<-miRNAset.list
  
  for (i in 1:length(miRNAset.list)){
    names(miRNAs_fgsea.gmt)[i]<-miRNAset.list[i]
    isomirset.df2.i<-data_df_given[data_df_given$parent==miRNAset.list[i],c("parent","UID")]
    fgsea2.gmt.i <- isomirset.df2.i %>% split(x = .$UID, f = .$parent)
    isomirset2.i<-paste(data_df_given$UID[data_df_given$parent==miRNAset.list[i]],collapse='\t')
    miRNAset.i<-c(name=miRNAset.list[i],description="miRTOP_miRNA",ids=isomirset2.i)
    miRNAs_GSEA.gmt<-bind_rows(miRNAs_GSEA.gmt,miRNAset.i)
    miRNAs_fgsea.gmt[i]<-fgsea2.gmt.i
  }
  
  print ("+ Save geneset in file:")
  file_name_miRNAs_GSEA.gmt = file.path(path2store_results, paste0(name, "_iso2miRNA.gmt"))
  print (file_name_miRNAs_GSEA.gmt)
  write.table(miRNAs_GSEA.gmt, file_name_miRNAs_GSEA.gmt,sep="\t",row.names=F,col.names=F, quote=F)
  
  ## miRNAs_fgsea.gmt
  print ("+ Gene set generated for miRNA-isomiR correspondence")
  print (head(miRNAs_fgsea.gmt))
  
  ## return data
  return_list = list("geneSet_stats" = geneSet_stats, 
                     "types_fgsea.gmt" = types_fgsea.gmt, 
                     "miRNAs_fgsea.gmt" = miRNAs_fgsea.gmt)
  
  return (return_list)
}

